### ISSUE TITLE
Dependencies needed for tv-headend

### ISSUE THREAD

**Issue by alex-martel** [xbianonpi/xbian-package-tvheadend#1]
There is a small typo in the last commit, package should be "dtv-scan-tables". In the curent situation the package is not installable since dvb-scan-tables does not exists. With this it allows pre-defined muxes for channel scan. Also "xmltv-util" would need to be a dependency otherwise all the epg grabbers in /usr/bin are not visible / usable by tv headend.

**Comment by mkreisl** [comment]
@manofthepeace 
Thanks for informing. I've fixed this and a new build is running. New packages should be available at 20:00 CET

**Comment by alex-martel** [comment]
Wow thanks for the ultra fast feedback. Will retest once available.
